// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package Config

import (
	"github.com/google/wire"
	"webservice-pattern/Controllers"
	"webservice-pattern/Repositories"
	"webservice-pattern/Services"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImplement := Repositories.UserRepositoryInit(gormDB)
	userServiceImplement := Services.UserServiceInit(userRepositoryImplement)
	userControllerImplement := Controllers.UserControllerInit(userServiceImplement)
	roleRepositoryImplement := Repositories.RoleRepositoryInit(gormDB)
	initialization := NewInitialization(userRepositoryImplement, userServiceImplement, userControllerImplement, roleRepositoryImplement)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var userServiceSet = wire.NewSet(Services.UserServiceInit, wire.Bind(new(Services.UserService), new(*Services.UserServiceImplement)))

var userRepoSet = wire.NewSet(Repositories.UserRepositoryInit, wire.Bind(new(Repositories.UserRepository), new(*Repositories.UserRepositoryImplement)))

var userCtrlSet = wire.NewSet(Controllers.UserControllerInit, wire.Bind(new(Controllers.UserController), new(*Controllers.UserControllerImplement)))

var roleRepoSet = wire.NewSet(Repositories.RoleRepositoryInit, wire.Bind(new(Repositories.RoleRepository), new(*Repositories.RoleRepositoryImplement)))
